title = "Chicago Human+AI Lab (CHAI)"
baseURL = "https://chicagohai.github.io"
theme = "researcher"
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
disableKinds = ["taxonomy", "term"]

[params]
titleAbbr = "CHAI"
author = "CHAI"
description = "CHAI is a research lab working on developing the best AI for humans at the University of Chicago."
favicon = "favicon.ico"  # path to a .ico to use as favicon
css = ["css/custom.css"]
googleAnalytics = "UA-186917619-1"
footer = { text = "A warm cup of CHAI" }


[permalinks]
"/" = "/:filename"

[menu]

[[menu.main]]
  name = "People"
  url = "/people"
  weight = 1

[[menu.main]]
  name = "Demos"
  url = "/demos"
  weight = 2

[[menu.main]]
  name = "News"
  url = "/news"
  weight = 3

[[menu.main]]
  name = "Pub"
  url = "/publication"
  weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
