name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: true

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: '0.114.0'
            extended: true

        - name: Build
          run: hugo --minify

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: github.ref == 'refs/heads/dev'
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public